version: '3'


services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network


  voting-app:
    build:
      context: ./voting-app
    container_name: voting-app
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
      - recommendation-engine
    networks:
      - app-network


  recommendation-engine:
    build:
      context: ./recommendation-engine
    container_name: recommendation-engine
    ports:
      - "5001:5001"
    depends_on:
      - redis
    networks:
      - app-network


networks:
  app-network:
    driver: bridge